
== Chain of Responsibility

[plantuml, diagram-chain-classes, png]
....

interface ChainElement<T>
class AbstractChainElement<T>
class AbstractIOFileChainElement
class DuplicateSearchElement
class FilterElement
class PrintElement
class StatisticElement

ChainElement <|-- AbstractChainElement
AbstractChainElement <|-- AbstractIOFileChainElement
AbstractIOFileChainElement <|-- DuplicateSearchElement
AbstractIOFileChainElement <|-- FilterElement
AbstractIOFileChainElement <|-- PrintElement
AbstractIOFileChainElement <|-- StatisticElement
....


[plantuml, diagram-chain-classes-aggregation, png]
....
left to right direction

FilterElement o-- DuplicateSearchElement
DuplicateSearchElement o-- StatisticElement
StatisticElement o-- PrintElement
....

== Command


[plantuml, diagram-command-classes, png]
....
interface Command
class AbstractCommand
class MoveCommand
class CopyCommand

Command <|-- AbstractCommand
AbstractCommand <|-- MoveCommand
AbstractCommand <|-- CopyCommand
Command : getSuccessor()
Command : execute(fs)
Command : undo(fs)
AbstractCommand : getCommandOptions()
....

[plantuml, diagram-command-classes-aggregation, png]
....
left to right direction

MoveCommand_1 o-- MoveCommand_2
MoveCommand_2 o-- CopyCommand_3

MoveCommand_1 : getSuccessor()
MoveCommand_2 : getSuccessor()
CopyCommand_3 : getSuccessor()
....
